default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: tbontb
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: k8sflow_development


test:
  <<: *default
  database: k8sflow_test

production:
  <<: *default
  database: k8sflow_production
  username: k8sflow
  password: <%= ENV['K8SFLOW_DATABASE_PASSWORD'] %>
