# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3319ac6af6046777297e9d7537228f7c092a0b1b8c3af0e01e03dac743e46bb7f13c179c6028558f1835062e0db57e400dc217e40215a2a505ee34ff926d6a45

test:
  secret_key_base: 205bd7c047b7b12a98c536bf1e91df39433c2771f5ea875aa8727156513b11ec1f834b84600fc10f5b99d0d14717102aa374d21ef2bd58dfe3e94264e13d5664

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
